// Generated by Wrangler on Fri Aug 30 2024 16:53:38 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	links: KVNamespace;
	LINKS_KV_NAMESPACE: "links";
	DEFAULT_REDIRECT: "https://nerdywoffy.me";
}
